<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BuildTools/**" />
    <Content Remove="BuildTools/**" />
    <None Remove="BuildTools/**" />
  </ItemGroup>

  <Target Name="BundleClientApp" BeforeTargets="Build" Condition="'$(DesignTimeBuild)' != 'true'">
    <Exec Command="dotnet run --project &quot;$(MSBuildProjectDirectory)/BuildTools/SymposiaInboxWeb.FrontendBuilder.csproj&quot; -- &quot;$(MSBuildProjectDirectory)&quot;" />
  </Target>

  <ItemGroup>
    <Content Update="Config/accounts.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="wwwroot/**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
