using System.Text;

if (args.Length != 1)
{
    Console.Error.WriteLine("Usage: SymposiaInboxWeb.FrontendBuilder <project-root>");
    return 1;
}

var projectRoot = Path.GetFullPath(args[0]);
var clientRoot = Path.Combine(projectRoot, "ClientApp");
var distRoot = Path.Combine(projectRoot, "wwwroot", "dist");

var bundleInputs = new[]
{
    Path.Combine(clientRoot, "vendor", "react.production.min.js"),
    Path.Combine(clientRoot, "vendor", "react-dom.production.min.js"),
    Path.Combine(clientRoot, "src", "app.js")
};

var cssInput = Path.Combine(projectRoot, "wwwroot", "styles.css");

foreach (var input in bundleInputs.Append(cssInput))
{
    if (!File.Exists(input))
    {
        Console.Error.WriteLine($"Required frontend asset was not found: {input}");
        return 2;
    }
}

Directory.CreateDirectory(distRoot);

var bundleBuilder = new StringBuilder();
bundleBuilder.AppendLine("/* Symposia Inbox Web bundle - generated by SymposiaInboxWeb.FrontendBuilder */");
foreach (var input in bundleInputs)
{
    bundleBuilder.AppendLine();
    bundleBuilder.AppendLine($"/* Source: {Path.GetRelativePath(projectRoot, input)} */");
    bundleBuilder.AppendLine(await File.ReadAllTextAsync(input));
}

var jsOutputPath = Path.Combine(distRoot, "app.bundle.js");
await File.WriteAllTextAsync(jsOutputPath, bundleBuilder.ToString());

var cssOutputPath = Path.Combine(distRoot, "app.css");
await File.WriteAllTextAsync(
    cssOutputPath,
    "/* Symposia Inbox Web stylesheet - generated by SymposiaInboxWeb.FrontendBuilder */\n\n" + await File.ReadAllTextAsync(cssInput));

Console.WriteLine($"Wrote {Path.GetRelativePath(projectRoot, jsOutputPath)}");
Console.WriteLine($"Wrote {Path.GetRelativePath(projectRoot, cssOutputPath)}");
return 0;
